Update lint-shell.yml

diff --git a/.github/workflows/lint-shell.yml b/.github/workflows/lint-shell.yml
--- a/.github/workflows/lint-shell.yml
+++ b/.github/workflows/lint-shell.yml
@@ -25,7 +25,13 @@ jobs:
         with:
           files: "**.sh"
 
+      # Debugging step to check the modified files in the PR branch
+      - name: Debug Modified Files
+        run: |
+          echo "Modified files: ${{ steps.changed-files.outputs.all_changed_files }}"
+
       - name: Run ShellCheck
+        continue-on-error: true # Allow continuing even if ShellCheck fails
         if: steps.changed-files.outputs.any_changed == 'true'
         run: |
           IFS=' '  # Set IFS to space to split the list correctly
@@ -35,6 +41,7 @@ jobs:
           done
         
       - name: Run shfmt and Check for Formatting Issues
+        continue-on-error: true # Allow continuing even if shfmt fails
         if: steps.changed-files.outputs.any_changed == 'true'
         run: |
           IFS=' '  # Set IFS to space to split the list correctly
@@ -47,3 +54,9 @@ jobs:
               }
           done
 
+        # This step will only run if any previous step failed
+      - name: Fail Job if There Were Errors
+        if: failure()
+        run: |
+          echo "There were errors detected in the scripts. Please review the output above."
+          exit 1
